-- NU:TONIC catalog SQL seed (IMP-120) — generated by data/scripts/sync_server_catalog.py --mode sql
-- Re-run safe: tables use CREATE IF NOT EXISTS + DELETE + INSERT.
BEGIN TRANSACTION;

CREATE TABLE IF NOT EXISTS nutonic_catalog_meta (
  singleton INTEGER PRIMARY KEY CHECK (singleton = 1),
  content_version TEXT NOT NULL,
  engine_version TEXT
);

CREATE TABLE IF NOT EXISTS nutonic_catalog_maps (
  map_id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  engine_version TEXT,
  content_version TEXT
);

CREATE TABLE IF NOT EXISTS nutonic_catalog_locations (
  map_id TEXT NOT NULL,
  location_id TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  PRIMARY KEY (map_id, location_id)
);

CREATE TABLE IF NOT EXISTS nutonic_catalog_ai_guesses (
  map_id TEXT NOT NULL,
  location_id TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  PRIMARY KEY (map_id, location_id)
);

DELETE FROM nutonic_catalog_ai_guesses;
DELETE FROM nutonic_catalog_locations;
DELETE FROM nutonic_catalog_maps;
DELETE FROM nutonic_catalog_meta;

INSERT INTO nutonic_catalog_meta (singleton, content_version, engine_version) VALUES (1, 'nutonic.manifest.v2', '0.1.0');

INSERT INTO nutonic_catalog_maps (map_id, title, engine_version, content_version) VALUES ('demo', 'Demo mission', '0.1.0', NULL);
INSERT INTO nutonic_catalog_maps (map_id, title, engine_version, content_version) VALUES ('idempotency-map', 'Lab · idempotency fixture', '0.1.0', NULL);

INSERT INTO nutonic_catalog_locations (map_id, location_id, payload_json) VALUES ('demo', 'demo-vienna-001', '{"ai_marker_phase_enabled":true,"location_id":"demo-vienna-001","map_id":"demo","play_budget_ms":180000,"ruleset_version":"nutonic.ruleset.v1","satellite_caption_sidecar":{"caption":"Mapbox still ortho \u2014 river-basin capital block pattern and ring roads (no coordinates).","model_id":"stub-v1","pipeline":"stub"},"still_bundle_id":"nutonic.bundle.v1.demo_still","still_bundled_resource":"files/3.jpg","still_http_url":null,"streetview_assist_narrative":null,"streetview_hint_pack":[{"rank":1,"text":"Pre-cached assist: broad European river-basin capital with historic core and ring boulevards.","viewpoint_id":null},{"rank":2,"text":"Assist: temperate continental climate cues; dense inner city with tram-era street furniture.","viewpoint_id":null}],"truth_lat":48.2082,"truth_lon":16.3738,"useful_hints":{"tier_1":"Western edge of the Eurasian landmass near Atlantic influence.","tier_2":"Alpine foothill capital on a major river north-east of high peaks.","tier_3":"Danube corridor; continental climate transition zone.","tier_4":"Eastern Alpine foreland and basin city layout.","tier_5":"Austria \u2014 central European country context.","tier_6":"Vienna-scale metro cues without coordinates (river-basin capital pattern)."}}');
INSERT INTO nutonic_catalog_locations (map_id, location_id, payload_json) VALUES ('idempotency-map', 'idempo-nyc-001', '{"ai_marker_phase_enabled":true,"location_id":"idempo-nyc-001","map_id":"idempotency-map","play_budget_ms":180000,"ruleset_version":"nutonic.ruleset.v1","satellite_caption_sidecar":null,"still_bundle_id":"nutonic.still.v1.idempo_nyc","still_bundled_resource":"files/3.jpg","still_http_url":null,"streetview_assist_narrative":null,"streetview_hint_pack":[{"rank":1,"text":"Pre-cached assist: dense island street grid with mid-rise masonry and steel-bridge skyline glimpses.","viewpoint_id":null}],"truth_lat":40.7128,"truth_lon":-74.006,"useful_hints":{"tier_1":"Eastern North American coastal megacity region.","tier_2":"Compact island grid between two tidal rivers.","tier_3":"Atlantic seaboard humid subtropical / continental blend.","tier_4":"Dense urban estuary with bridge-linked boroughs.","tier_5":"United States \u2014 northeastern megalopolis corridor.","tier_6":"Iconic island-core coastal megacity pattern (no coordinate literals)."}}');

INSERT INTO nutonic_catalog_ai_guesses (map_id, location_id, payload_json) VALUES ('demo', 'demo-vienna-001', '{"ai_lat":41.9028,"ai_lon":12.4964,"location_id":"demo-vienna-001","map_id":"demo"}');
INSERT INTO nutonic_catalog_ai_guesses (map_id, location_id, payload_json) VALUES ('idempotency-map', 'idempo-nyc-001', '{"ai_lat":51.5074,"ai_lon":-0.1278,"location_id":"idempo-nyc-001","map_id":"idempotency-map"}');

COMMIT;
