#!/usr/bin/env python3
"""
Emit ``server/src/nutonic_server/catalog_generated.py`` from ``manifest.full.json``.

Normative: docs/scripts/SPEC-sync-server-catalog.md
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST = (
    REPO_ROOT
    / "nutonic"
    / "shared"
    / "src"
    / "commonMain"
    / "composeResources"
    / "files"
    / "cache"
    / "manifest.full.json"
)
DEFAULT_OUT = REPO_ROOT / "server" / "src" / "nutonic_server" / "catalog_generated.py"

EXIT_INPUT = 2
EXIT_SCHEMA = 13

HEADER = '''# AUTO-GENERATED by data/scripts/sync_server_catalog.py — DO NOT EDIT.
# Regenerate: python data/scripts/sync_server_catalog.py --manifest <path> --write
from __future__ import annotations

import json

from nutonic_server.schemas import CacheManifestOut

_MANIFEST_JSON_STR = {json_literal}

_MANIFEST_DOC = CacheManifestOut.model_validate(json.loads(_MANIFEST_JSON_STR))
PUBLISHED_MAPS = list(_MANIFEST_DOC.maps)
MANIFEST_LOCATIONS = list(_MANIFEST_DOC.locations)
MANIFEST_AI_GUESSES = list(_MANIFEST_DOC.ai_guesses)
CATALOG_MANIFEST_CONTENT_VERSION = _MANIFEST_DOC.content_version
CATALOG_MANIFEST_ENGINE_VERSION = _MANIFEST_DOC.engine_version
'''


def _emit_py(manifest_path: Path) -> str:
    raw = json.loads(manifest_path.read_text(encoding="utf-8"))
    # Validate full server hydration shape
    sys.path.insert(0, str(REPO_ROOT / "server" / "src"))
    from nutonic_server.schemas import CacheManifestOut  # noqa: PLC0415

    doc = CacheManifestOut.model_validate(raw)
    canon = doc.model_dump_json(by_alias=True)
    json_literal = repr(canon)
    return HEADER.format(json_literal=json_literal)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Sync server catalog_generated.py from manifest.full.json")
    p.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST, help="Path to manifest.full.json")
    p.add_argument("--output", type=Path, default=DEFAULT_OUT, help="Output catalog_generated.py path")
    p.add_argument("--write", action="store_true", help="Write output file (default: print unified diff)")
    p.add_argument("--mode", choices=("codegen", "noop", "sql"), default="codegen")
    args = p.parse_args(argv)
    if args.mode == "noop":
        print("sync_server_catalog: noop", file=sys.stderr)
        return 0
    if args.mode == "sql":
        print("sync_server_catalog: sql mode not implemented (IMP-120)", file=sys.stderr)
        return 2
    if not args.manifest.is_file():
        print(f"Manifest not found: {args.manifest}", file=sys.stderr)
        return EXIT_INPUT
    try:
        text = _emit_py(args.manifest)
    except Exception as e:
        print(f"Manifest incompatible with CacheManifestOut: {e}", file=sys.stderr)
        return EXIT_SCHEMA
    if args.write:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8", newline="\n")
        print(f"Wrote {args.output}", file=sys.stderr)
        return 0
    prev = args.output.read_text(encoding="utf-8") if args.output.is_file() else ""
    diff = difflib.unified_diff(
        prev.splitlines(keepends=True),
        text.splitlines(keepends=True),
        fromfile=str(args.output) + " (existing)",
        tofile=str(args.output) + " (generated)",
    )
    sys.stdout.writelines(diff)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
