#!/usr/bin/env python3
"""
Emit ``server/src/nutonic_server/catalog_generated.py`` from ``manifest.full.json``.

Normative: docs/scripts/SPEC-sync-server-catalog.md

**IMP-081:** With ``--write`` (default), merge ``still_bundle_id`` rows into ``bundles/registry.json``
when ``bundles/{id}.jpg`` exists; preserve existing registry aliases. Use ``--no-update-bundle-registry``
to skip mutation (validation still runs on dry-run / write).

**IMP-120:** ``--mode sql`` emits SQLite-oriented DDL + DML for catalog rehearsal (optional DB load).
"""

from __future__ import annotations

import argparse
import difflib
import json
import sys
from pathlib import Path
from typing import Any

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_MANIFEST = (
    REPO_ROOT
    / "nutonic"
    / "shared"
    / "src"
    / "commonMain"
    / "composeResources"
    / "files"
    / "cache"
    / "manifest.full.json"
)
DEFAULT_OUT = REPO_ROOT / "server" / "src" / "nutonic_server" / "catalog_generated.py"
DEFAULT_SQL_OUT = REPO_ROOT / "server" / "docs" / "catalog_seed.sql"
BUNDLES_DIR = REPO_ROOT / "server" / "src" / "nutonic_server" / "bundles"
REGISTRY_PATH = BUNDLES_DIR / "registry.json"

EXIT_INPUT = 2
EXIT_SCHEMA = 13
EXIT_BUNDLE_REGISTRY = 14


class BundleRegistrySyncError(ValueError):
    """Manifest ``still_bundle_id`` cannot be resolved to bytes on disk under ``bundles/``."""


HEADER = '''# AUTO-GENERATED by data/scripts/sync_server_catalog.py — DO NOT EDIT.
# Regenerate: python data/scripts/sync_server_catalog.py --manifest <path> --write
from __future__ import annotations

import json

from nutonic_server.schemas import CacheManifestOut

_MANIFEST_JSON_STR = {json_literal}

_MANIFEST_DOC = CacheManifestOut.model_validate(json.loads(_MANIFEST_JSON_STR))
PUBLISHED_MAPS = list(_MANIFEST_DOC.maps)
MANIFEST_LOCATIONS = list(_MANIFEST_DOC.locations)
MANIFEST_AI_GUESSES = list(_MANIFEST_DOC.ai_guesses)
CATALOG_MANIFEST_CONTENT_VERSION = _MANIFEST_DOC.content_version
CATALOG_MANIFEST_ENGINE_VERSION = _MANIFEST_DOC.engine_version
'''


def _parse_manifest(manifest_path: Path) -> Any:
    raw = json.loads(manifest_path.read_text(encoding="utf-8"))
    sys.path.insert(0, str(REPO_ROOT / "server" / "src"))
    from nutonic_server.schemas import CacheManifestOut  # noqa: PLC0415

    return CacheManifestOut.model_validate(raw)


def _bundle_registry_misses(doc: object) -> list[str]:
    """Return ``still_bundle_id`` values from the manifest that are missing from ``bundles/registry.json``."""
    if not REGISTRY_PATH.is_file():
        return []
    reg = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    bundles = reg.get("bundles")
    if not isinstance(bundles, dict):
        return []
    known = frozenset(str(k) for k in bundles)
    missing: list[str] = []
    for loc in getattr(doc, "locations", []) or []:
        bid = (getattr(loc, "still_bundle_id", None) or "").strip()
        if bid and bid not in known:
            missing.append(bid)
    return sorted(frozenset(missing))


def _verify_registry_files(doc: object) -> None:
    """Ensure every registry mapping for manifest ``still_bundle_id``s points at an existing file."""
    if not REGISTRY_PATH.is_file():
        return
    reg = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
    bundles = reg.get("bundles")
    if not isinstance(bundles, dict):
        return
    bids = {
        (getattr(loc, "still_bundle_id", None) or "").strip()
        for loc in getattr(doc, "locations", []) or []
        if (getattr(loc, "still_bundle_id", None) or "").strip()
    }
    bad: list[str] = []
    for bid in bids:
        fname = bundles.get(bid)
        if not isinstance(fname, str) or not fname.strip():
            bad.append(f"{bid!r} (missing filename in registry)")
            continue
        if not (BUNDLES_DIR / fname.strip()).is_file():
            bad.append(f"{bid!r} -> {fname!r} (file missing under bundles/)")
    if bad:
        raise BundleRegistrySyncError("Bundle registry file problems (IMP-081): " + "; ".join(bad))


def merge_bundle_registry_from_manifest(doc: object) -> None:
    """
    Merge manifest ``still_bundle_id`` keys into ``registry.json``.

    - Preserves existing ``bundles`` entries not touched by the manifest (extra dev aliases).
    - For each manifest ``still_bundle_id``: keeps existing mapping if the target file exists;
      otherwise registers ``{id}.jpg`` when that file exists.
    """
    BUNDLES_DIR.mkdir(parents=True, exist_ok=True)
    prev: dict[str, str] = {}
    if REGISTRY_PATH.is_file():
        raw = json.loads(REGISTRY_PATH.read_text(encoding="utf-8"))
        b = raw.get("bundles")
        if isinstance(b, dict):
            prev = {str(k): str(v) for k, v in b.items()}

    merged = dict(prev)
    for loc in getattr(doc, "locations", []) or []:
        bid = (getattr(loc, "still_bundle_id", None) or "").strip()
        if not bid:
            continue
        if bid in merged:
            target = BUNDLES_DIR / merged[bid]
            if not target.is_file():
                raise BundleRegistrySyncError(
                    f"still_bundle_id {bid!r} maps to {merged[bid]!r} but file is missing under bundles/",
                )
            continue
        default_name = f"{bid}.jpg"
        default_path = BUNDLES_DIR / default_name
        if default_path.is_file():
            merged[bid] = default_name
        else:
            raise BundleRegistrySyncError(
                f"still_bundle_id {bid!r}: add JPEG at bundles/{default_name} "
                f"or add an explicit mapping in {REGISTRY_PATH.name} before sync.",
            )

    payload = {"bundles": dict(sorted(merged.items(), key=lambda kv: kv[0]))}
    REGISTRY_PATH.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8", newline="\n")


def _emit_py_from_doc(doc: Any) -> str:
    _verify_registry_files(doc)
    misses = _bundle_registry_misses(doc)
    if misses:
        raise BundleRegistrySyncError(
            "Manifest references still_bundle_id not listed in server .../bundles/registry.json (IMP-081): "
            + ", ".join(misses),
        )
    canon = doc.model_dump_json(by_alias=True)
    json_literal = repr(canon)
    return HEADER.format(json_literal=json_literal)


def _sql_escape_literal(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def _emit_sqlite_seed(doc: Any) -> str:
    """Portable SQLite seed: maps + JSON payloads for locations and AI rows (IMP-120 near-term)."""
    lines = [
        "-- NU:TONIC catalog SQL seed (IMP-120) — generated by data/scripts/sync_server_catalog.py --mode sql",
        "-- Re-run safe: tables use CREATE IF NOT EXISTS + DELETE + INSERT.",
        "BEGIN TRANSACTION;",
        "",
        "CREATE TABLE IF NOT EXISTS nutonic_catalog_meta (",
        "  singleton INTEGER PRIMARY KEY CHECK (singleton = 1),",
        "  content_version TEXT NOT NULL,",
        "  engine_version TEXT",
        ");",
        "",
        "CREATE TABLE IF NOT EXISTS nutonic_catalog_maps (",
        "  map_id TEXT PRIMARY KEY,",
        "  title TEXT NOT NULL,",
        "  engine_version TEXT,",
        "  content_version TEXT",
        ");",
        "",
        "CREATE TABLE IF NOT EXISTS nutonic_catalog_locations (",
        "  map_id TEXT NOT NULL,",
        "  location_id TEXT NOT NULL,",
        "  payload_json TEXT NOT NULL,",
        "  PRIMARY KEY (map_id, location_id)",
        ");",
        "",
        "CREATE TABLE IF NOT EXISTS nutonic_catalog_ai_guesses (",
        "  map_id TEXT NOT NULL,",
        "  location_id TEXT NOT NULL,",
        "  payload_json TEXT NOT NULL,",
        "  PRIMARY KEY (map_id, location_id)",
        ");",
        "",
        "DELETE FROM nutonic_catalog_ai_guesses;",
        "DELETE FROM nutonic_catalog_locations;",
        "DELETE FROM nutonic_catalog_maps;",
        "DELETE FROM nutonic_catalog_meta;",
        "",
    ]
    cv = _sql_escape_literal(str(doc.content_version))
    ev = doc.engine_version
    ev_sql = "NULL" if ev is None else _sql_escape_literal(str(ev))
    lines.append(
        f"INSERT INTO nutonic_catalog_meta (singleton, content_version, engine_version) "
        f"VALUES (1, {cv}, {ev_sql});",
    )
    lines.append("")
    for m in doc.maps:
        d = m.model_dump(by_alias=True)
        mid = _sql_escape_literal(str(d["map_id"]))
        title = _sql_escape_literal(str(d["title"]))
        eng = d.get("engine_version")
        ctv = d.get("content_version")
        eng_sql = "NULL" if eng is None else _sql_escape_literal(str(eng))
        ctv_sql = "NULL" if ctv is None else _sql_escape_literal(str(ctv))
        lines.append(
            "INSERT INTO nutonic_catalog_maps (map_id, title, engine_version, content_version) "
            f"VALUES ({mid}, {title}, {eng_sql}, {ctv_sql});",
        )
    lines.append("")
    for loc in doc.locations:
        d = loc.model_dump(by_alias=True)
        mid = _sql_escape_literal(str(d["map_id"]))
        lid = _sql_escape_literal(str(d["location_id"]))
        payload = json.dumps(d, sort_keys=True, separators=(",", ":"))
        pj = _sql_escape_literal(payload)
        lines.append(
            "INSERT INTO nutonic_catalog_locations (map_id, location_id, payload_json) "
            f"VALUES ({mid}, {lid}, {pj});",
        )
    lines.append("")
    for row in doc.ai_guesses:
        d = row.model_dump(by_alias=True)
        mid = _sql_escape_literal(str(d["map_id"]))
        lid = _sql_escape_literal(str(d["location_id"]))
        payload = json.dumps(d, sort_keys=True, separators=(",", ":"))
        pj = _sql_escape_literal(payload)
        lines.append(
            "INSERT INTO nutonic_catalog_ai_guesses (map_id, location_id, payload_json) "
            f"VALUES ({mid}, {lid}, {pj});",
        )
    lines.extend(["", "COMMIT;", ""])
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description="Sync server catalog_generated.py from manifest.full.json")
    p.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST, help="Path to manifest.full.json")
    p.add_argument("--output", type=Path, default=DEFAULT_OUT, help="Output catalog_generated.py path")
    p.add_argument(
        "--sql-output",
        type=Path,
        default=DEFAULT_SQL_OUT,
        help="Output path for --mode sql (IMP-120)",
    )
    p.add_argument("--write", action="store_true", help="Write output file(s); without it, print diff or SQL")
    p.add_argument("--mode", choices=("codegen", "noop", "sql"), default="codegen")
    p.add_argument(
        "--no-update-bundle-registry",
        action="store_true",
        help="With --write + codegen: do not merge bundles/registry.json from manifest (IMP-081)",
    )
    args = p.parse_args(argv)
    if args.mode == "noop":
        print("sync_server_catalog: noop", file=sys.stderr)
        return 0
    if not args.manifest.is_file():
        print(f"Manifest not found: {args.manifest}", file=sys.stderr)
        return EXIT_INPUT

    if args.mode == "sql":
        try:
            doc = _parse_manifest(args.manifest)
        except Exception as e:
            print(f"Manifest incompatible with CacheManifestOut: {e}", file=sys.stderr)
            return EXIT_SCHEMA
        sql = _emit_sqlite_seed(doc)
        if args.write:
            args.sql_output.parent.mkdir(parents=True, exist_ok=True)
            args.sql_output.write_text(sql, encoding="utf-8", newline="\n")
            print(f"Wrote {args.sql_output}", file=sys.stderr)
        else:
            sys.stdout.write(sql)
        return 0

    try:
        doc = _parse_manifest(args.manifest)
        if args.write and not args.no_update_bundle_registry:
            merge_bundle_registry_from_manifest(doc)
        text = _emit_py_from_doc(doc)
    except BundleRegistrySyncError as e:
        print(str(e), file=sys.stderr)
        return EXIT_BUNDLE_REGISTRY
    except Exception as e:
        print(f"Manifest incompatible with CacheManifestOut: {e}", file=sys.stderr)
        return EXIT_SCHEMA
    if args.write:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(text, encoding="utf-8", newline="\n")
        print(f"Wrote {args.output}", file=sys.stderr)
        return 0
    prev = args.output.read_text(encoding="utf-8") if args.output.is_file() else ""
    diff = difflib.unified_diff(
        prev.splitlines(keepends=True),
        text.splitlines(keepends=True),
        fromfile=str(args.output) + " (existing)",
        tofile=str(args.output) + " (generated)",
    )
    sys.stdout.writelines(diff)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
